# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# 对于我们使用cocoapod引入的第三方,我们可以在podfile文件中 增加一句  inhibit_all_warnings! 来要pod的工程不显示任何警告
inhibit_all_warnings!

target 'GMStore-iOS' do
    # use_frameworks!
    
    pod 'SVProgressHUD'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'SDCycleScrollView'
    pod 'FMDB'
    pod 'ZYCornerRadius'
    pod 'SDWebImage'
    pod 'TZImagePickerController'
    pod 'IQKeyboardManager'
    pod 'AFNetworking'
    pod 'CDDPagerController'
    pod 'PureLayout'
    pod 'PPNumberButton'
    
    
    pod 'YJHomeKit', :path=> '../../YJHomeKit'
#    pod 'YJHomeKit'

end
